2021-05-12T23:22:23,323 Using pip 21.1.1 from /Users/tk/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip (python 3.9)
2021-05-12T23:22:23,324 Non-user install because site-packages writeable
2021-05-12T23:22:23,325 Created temporary directory: /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-ephem-wheel-cache-j1yndvo2
2021-05-12T23:22:23,326 Created temporary directory: /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-req-tracker-nqwhns4g
2021-05-12T23:22:23,326 Initialized build tracking at /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-req-tracker-nqwhns4g
2021-05-12T23:22:23,326 Created build tracker: /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-req-tracker-nqwhns4g
2021-05-12T23:22:23,326 Entered build tracker: /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-req-tracker-nqwhns4g
2021-05-12T23:22:23,326 Created temporary directory: /private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-install-_6ooz9h_
2021-05-12T23:22:23,326 ERROR: You must give at least one requirement to install (see "pip help install")
2021-05-12T23:22:23,326 Exception information:
2021-05-12T23:22:23,326 Traceback (most recent call last):
2021-05-12T23:22:23,326   File "/Users/tk/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
2021-05-12T23:22:23,326     status = self.run(options, args)
2021-05-12T23:22:23,326   File "/Users/tk/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
2021-05-12T23:22:23,326     return func(self, options, args)
2021-05-12T23:22:23,326   File "/Users/tk/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 289, in run
2021-05-12T23:22:23,326     reqs = self.get_requirements(args, options, finder, session)
2021-05-12T23:22:23,326   File "/Users/tk/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 415, in get_requirements
2021-05-12T23:22:23,326     raise CommandError(
2021-05-12T23:22:23,326 pip._internal.exceptions.CommandError: You must give at least one requirement to install (see "pip help install")
2021-05-12T23:22:23,330 Removed build tracker: '/private/var/folders/l2/6_2vxyc15zl6rb3mnjl4688m0000gn/T/pip-req-tracker-nqwhns4g'
